# Generated by Django 3.1.4 on 2020-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blocks',
            fields=[
                ('blocks_id', models.PositiveIntegerField(db_column='blocks_id', default=-1, primary_key=True, serialize=False)),
                ('seq', models.TextField()),
                ('ip_values', models.TextField()),
            ],
        ),
    ]
