# Generated by Django 3.1.4 on 2020-12-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outputplot',
            fields=[
                ('outputplot_id', models.PositiveIntegerField(db_column='id', default=-1, primary_key=True, serialize=False)),
                ('x', models.TextField()),
                ('y', models.TextField()),
            ],
        ),
    ]
