# Generated by Django 3.1.4 on 2021-02-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_outputplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputplot',
            name='typeOfAnalysis',
            field=models.CharField(default='ac', max_length=200),
            preserve_default=False,
        ),
    ]
