# Generated by Django 3.1.4 on 2021-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_outputplot_typeofanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgspiceCode',
            fields=[
                ('code_id', models.PositiveIntegerField(db_column='code_id', default=-1, primary_key=True, serialize=False)),
                ('code', models.TextField()),
            ],
        ),
    ]
