# Generated by Django 3.1.4 on 2021-02-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ngspicecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(db_column='user_id', max_length=200, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('email_id', models.TextField()),
            ],
        ),
    ]
