# Generated by Django 3.1.4 on 2021-02-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='blocks_id',
            field=models.CharField(db_column='blocks_id', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ngspicecode',
            name='code_id',
            field=models.CharField(db_column='code_id', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outputplot',
            name='outputplot_id',
            field=models.CharField(db_column='outputplot_id', max_length=200, primary_key=True, serialize=False),
        ),
    ]
