# Generated by Django 3.1.4 on 2021-02-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210205_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='circuit_name',
            field=models.TextField(default='circuit1'),
        ),
        migrations.AddField(
            model_name='ngspicecode',
            name='circuit_name',
            field=models.TextField(default='circuit1'),
        ),
        migrations.AddField(
            model_name='outputplot',
            name='circuit_name',
            field=models.TextField(default='circuit1'),
        ),
    ]
