# Generated by Django 3.1.4 on 2021-03-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210209_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='formlist',
            field=models.TextField(default=''),
        ),
    ]
